### ISSUE TITLE
NU1100 errors due to missing NuGet sources

### ISSUE THREAD

**Issue by GD-Mannheim** [carstenschaefer/FolderSecurityViewer#9]
i get many issues when i try to compile the sourcecode:

[Fehler.txt](https://github.com/user-attachments/files/16749420/Fehler.txt)

**Comment by matzefriedrich** [comment]
Hi @GD-Mannheim,

Thanks for opening an issue. The `dotnet build` command seems to have trouble restoring NuGet package dependencies, which is (most likely) a problem on your end since we build all source code on push via GitHub actions without issues.

The build uses the `net8.0-window7.0` TFM moniker, which is not used by any project configurations. Sometimes, this might be an issue with an outdated package cache, a false NuGet configuration, pure networking issues, problems related to preview, unsupported SDK versions, etc.

Regarding platform compatibility, please take a look at the information at https://github.com/carstenschaefer/FolderSecurityViewer#platform-compatibility.

I'm sorry, but the attached error log does not contain any information we could use to resolve the problems. Please investigate this further, and please do not hesitate to come back as soon as you find something I can help with.

**Comment by matzefriedrich** [comment]
According to the log, the build fails due to the NuGet error `NU1100`, a generic issue. I´d recommend referring to the official documentation at https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1100

**Comment by matzefriedrich** [comment]
Just in case you do not have a Visual Studio 2022 installation but only the .NET 8 SDK, the NuGet configuration may not have any package sources registered, leading to the error `NU1100` when running `dotnet build` or `dotnet restore` commands. You can list available package sources via:

````sh
dotnet nuget list source
````

If running `dotnet nuget list source` does not return any sources, your NuGet configuration is missing the default public NuGet feed. You can add it manually using the following command:

````sh
dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
````

Try to rerun the build.
